export const SERVER_URI_GRAPHQL = 'https://api.betascratch.com/graphql'
export const SERVER_URI_REST = 'https://api.betascratch.com/api'
export const SERVER_URI_UPLOAD = 'https://api.betascratch.com/api/game'
// export const SERVER_URI_GRAPHQL = 'http://localhost:4000/graphql'
// export const SERVER_URI_REST = 'https://localhost:4000/api'
